import Navbar from "@/components/navbar/Navbar";
import { Outfit as FontSans } from "next/font/google";
import "../globals.css";
import Footer from "@/components/footer/Footer";
import BackToTop from "@/components/shared/BackToTop/BackToTop";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <Navbar />
        {children}
        <Footer/>
        <BackToTop />
      </body>
    </html>
  );
}
